= Quarkus Health as Metrics

Expose the health status of the application as metrics.

When activated, the extension provides the following new metrics:

.New metrics for default groups
[code]
----
application_status{group="health",status="UP"}         # corresponds to /q/health
application_status{group="live",status="UP"}           # corresponds to /q/health/live
application_status{group="ready",status="UP"}          # corresponds to /q/health/ready
application_status{group="startup",status="UP"}        # corresponds to /q/health/started
application_status{group="well",status="UP"}           # corresponds to /q/health/well

application_status{group="health",status="DOWN"}       # corresponds to /q/health
application_status{group="live",status="DOWN"}         # corresponds to /q/health/live
application_status{group="ready",status="DOWN"}        # corresponds to /q/health/ready
application_status{group="startup",status="DOWN"}      # corresponds to /q/health/started
application_status{group="well",status="DOWN"}         # corresponds to /q/health/well
----

Additionally, for all custom groups, a pair of checks will be created:

.New metrics for custom groups
[code]
----
application_status{group="<group-name>",status="UP"}   # corresponds to /q/health/group/<group-name>

application_status{group="<group-name>",status="DOWN"} # corresponds to /q/health/group/<group-name>
----

Next, for each `HealthCheck`, an additional pair of metrics is provided:

.New metrics for custom health checks
[code]
----
application_health_check{check="<health-check-name>",status="UP"}

application_health_check{check="<health-check-name>",status="DOWN"}
----

Finally, for each date within a check, that "can be parsed", a separate metrics-pair is created. As of now, the following dates can be parsed:
- any key, and value is either `"UP"` or `"DOWN"`
- any key, and value is either `"READY"` or `"NOT READY"`
- any key, and value is a boolean
- any key, and value is a long, where `0L` means `DOWN` and any other value means `UP`.

The class link:integration-tests/commons/src/main/java/de/turing85/quarkus/health/as/metrics/it/commons/CustomHealthCheck.java[`CustomHealthCheck.java`] defines three dates within its check:

.Health check definition of `CustomHealthCheck.java`
[code, java]
----
...
public class CustomHealthCheck implements HealthCheck {
  private boolean isHealthy = true;

  @Override
  public HealthCheckResponse call() {
    // @formatter:off
    return HealthCheckResponse
        .named("custom")
        .status(isHealthy())
        .withData("inner1", isHealthy() ? "UP" : "DOWN")
        .withData("inner2", isHealthy() ? "READY" : "NOT READY")
        .withData("inner3", isHealthy())
        .withData("inner4", isHealthy() ? 1337L : 0L)
        .build();
    // @formatter:on
  }
}
----

For the three date entries, the following six metrics are created:

.New metrics for check data
[code]
----
"application_health_check{check=\"custom-inner1\",status=\"UP\"}"
"application_health_check{check=\"custom-inner2\",status=\"UP\"}"
"application_health_check{check=\"custom-inner3\",status=\"UP\"}"
"application_health_check{check=\"custom-inner4\",status=\"UP\"}"

"application_health_check{check=\"custom\",status=\"DOWN\"}"
"application_health_check{check=\"custom-inner1\",status=\"DOWN\"}"
"application_health_check{check=\"custom-inner2\",status=\"DOWN\"}"
"application_health_check{check=\"custom-inner3\",status=\"DOWN\"}"
"application_health_check{check=\"custom-inner4\",status=\"DOWN\"}"
----

As we see, the name for the date is the check's name (`"custom"`), followed by the date's name (`"inner1"`, `"inner"2`, or `"inner3"`)

When the corresponding check is up, the metric with `...,status="UP"` will have a value of `1.0`, and the corresponding metric with `...,status="DOWN"` will have a value of `0.0`.

When the corresponding check is up, the metric with `...,status="UP"` will have a value of `0.0`, and the corresponding metric with `...,status="DOWN"` will have a value of `1.0`.

== Example data

The Quarkus- and Quarkus tests are exhaustive. To see the full set of data, I encourage you to look at link:integration-tests/health-enabled/src/test/java/de/turing85/quarkus/health/as/metrics/it/health/enabled/HealthMetricsTest.java[`HealthMetricsTest.java`], the `@CsvSource` annotations shows all metrics in their expected state when the corresponding check is up or down.

== Contributors ✨

Thanks goes to these wonderful people (https://allcontributors.org/docs/en/emoji-key[emoji key]):

++++
<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- prettier-ignore-start -->
<!-- markdownlint-disable -->
<table>
  <tbody>
    <tr>
      <td align="center" valign="top" width="14.28%"><a href="https://turing85.github.io"><img src="https://avatars.githubusercontent.com/u/32584495?v=4?s=100" width="100px;" alt="Marco Bungart"/><br /><sub><b>Marco Bungart</b></sub></a><br /><a href="#code-turing85" title="Code">💻</a> <a href="#maintenance-turing85" title="Maintenance">🚧</a> <a href="#doc-turing85" title="Documentation">📖</a></td>
    </tr>
  </tbody>
</table>

<!-- markdownlint-restore -->
<!-- prettier-ignore-end -->

<!-- ALL-CONTRIBUTORS-LIST:END -->
++++